### ISSUE TITLE
CGNS currently has a 4GB limit on windows

### ISSUE THREAD

**Issue by scharlton2** [i-RIC/iricdev#5]
CGNS versions prior to 3.3.2 have a file size limitation of 4GB. See [CGNS-83](https://cgnsorg.atlassian.net/browse/CGNS-83).  We should start using cgns-3.3.2 as soon as it becomes stable (As of 2018-03-15 3.3.1 is the current stable release).

Note: A temporary workaround would be to use the DIVIDESOLUTIONS option within the affected solver:

    call iric_initoption_f(IRIC_OPTION_DIVIDESOLUTIONS, ier)

As long as each time step is less than 4GB.

This will require an update to the developer 64-bit libraries for intel fortran (Windows) .

**Comment by kskinoue0612** [comment]
Hi Scott,

Reviewing the issues, I've noticed that this issue is finished, thanks to closing the following issue.
https://github.com/i-RIC/prepost-gui/issues/286

So, I close this issue.
Thanks,
Keisuke
